language: python
python:
  - '3.6'
env:
  - DB_NAME=archive DB_USER=postgres DB_PASS=
install:
  - pip install -r requirements.txt
addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6-postgis-2.4
before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -c 'create database archive;' -U postgres
script:
  - python manage.py test
