web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
        - .:/app
    ports:
        - "8000:8000"
    links:
        - postgres

postgres:
    image: oslandia/pggis
    ports:
        - "5432:5432"
    command: /sbin/my_init
