# Helm chart values for production deployment of lco/archiveapi

# This service is very important to LCO, so we will run lots of replicas.
replicaCount: 3

gunicornTimeout: 30
gunicornWorkers: 4

applyDatabaseMigrations: true

aws:
  defaultRegion: "us-west-2"
  s3Bucket: "archive.lcogt.net"

# NGINX webserver configuration parameters.
nginx:
  # Resource requests/limits
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi

# Python backend configuration parameters. We use AWS credentials with
# read-write access to the AWS S3 Bucket archive.lcogt.net.
backend:
  # Resource requests/limits
  resources:
    requests:
      cpu: 100m
      memory: 384Mi
    limits:
      cpu: 2000m
      memory: 1024Mi

# PostgreSQL database credentials
postgresql:
  hostname: "postgres1-cluster.cluster-cple9sjsskrf.us-west-2.rds.amazonaws.com"
  postgresqlDatabase: "archive"
  postgresqlUsername: "archive"
  postgresqlPassword: "WVLnBTaPNPyVa5LPQvt"

# Bosun configuration parameters
bosunHostname: "alerts.lco.gtn"

# OpenTSDB configuration parameters
opentsdbHostname: "opentsdb.lco.gtn"

# Purge Quicklook data CronJob
purgeQuicklook:
  enabled: true

# Ingress (HTTP traffic)
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress-public
  hosts:
    - "archive-api.lco.global"
