name: Build

on:
  # Run this workflow for pushes on all branches
  push:
    branches:
      - '**'
  # Run this workflow when a tag or branch is created
  create:
  # Run this workflow for pull requests
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    services:
      postgres:
        image: postgis/postgis:9.6-2.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and setup
      run: |
        sudo apt-get -y update
        sudo apt-get install gdal-bin
        python -m pip install --upgrade pip
        pip install -r .poetry-version
        pip install -r <(poetry export --with dev)
    - name: Run tests
      run: poetry run coverage run manage.py test --settings=test_settings
      env:
        DB_USER: postgres
        DB_PASS: postgres
        DB_HOST: 127.0.0.1
        DB_HOST_READER: 127.0.0.1
        DB_PORT: 5432
    - name: Generate and send coveralls report
      run: poetry run coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
